### PR TITLE
Add 'select delivery method' option to mail notifier

### PR DESCRIPTION
**Pull request by brain-geek**

### CODE REVIEW

**Comment by brain-geek** [comment]
Updated pull request. Moved tests from integrated sinatra app to fakeweb, it made tests little easier to understand. Idea is not mine, taken from bug #6 - and this bug is now fixed. :)

**Comment by brain-geek** [comment]
Add feature for request head instead of all file contents. @vinibaggio , is it possible to release this code in new version of gem?

**Comment by vinibaggio** [comment]
@brain-geek hey man, I'm swamped :( Sorry! Would it help you if I added you to the outpost gem as a direct contributor? So you do the code directly in the repo

**Comment by brain-geek** [comment]
@vinibaggio Yes, it would help greatly, if I could release new versions of gem and contribute directly to repo.

**Comment by vinibaggio** [comment]
Done! I will see how can I add you as a collab in rubygems

**Comment by brain-geek** [comment]
Ok, thank you for help!

**Pull request merged**
