### PR TITLE
Add tcp scout

### PR DESCRIPTION
**Pull request by brain-geek**
Added tcp scout for checking if port is open. It may need some enhancements, but looks like it works. 

Also, i`ve added net/ping to gem dependencies, as 'require 'outpost'' fails without it.

### CODE REVIEW

**Comment by brain-geek** [comment]
@vinibaggio is it possible to merge this commits(all or only functional changes, such as tcp scout) and release new version of outpost, so that i could release first version of my monitoring ui, which uses outpost as backend? :)

**Comment by vinibaggio** [comment]
of course! let me check if everything's ok.

**Comment by brain-geek** [comment]
@vinibaggio Thank you!

**Comment by vinibaggio** [comment]
No, I thank YOU for the great effort you're putting on outpost :-) :metal:

**Comment by brain-geek** [comment]
:)

**Comment by vinibaggio** [comment]
Released!

**Comment by brain-geek** [comment]
And I have question about TODO - what does 'SSH Support' mean?

**Comment by vinibaggio** [comment]
My plan was to retrieve information about a machine using SSH, such as filesystem usage, load, etc.

**Pull request merged**
